### PR TITLE
Add skeleton component to checkout

### PR DESCRIPTION
**Pull request by TiagoFuelber**
This PR creates a Skeleton component and applies it to the Checkout component

Links
-----
#514 

Jun-07-2024 11-07-46

Developer considerations
--------------

- On any task
  - [ ] Previous unit and e2e tests are passing
  - [ ] Perform dev QA
- On new features
  - [ ] Add unit tests
  - [ ] Add e2e tests
  - [ ] Add documentation
  - [ ] Does the component have exportedparts for styling? If so, add unit a unit test for each exportedpart
- On bugs
  - [ ] Add unit tests to prevent the bug from happening again

Developer QA steps
--------------------

### CODE REVIEW

**Comment by colganmeanor** [comment]
I'm not sure exactly what changed - but something here is affecting the size or styling for some of the text elements on the component. 

It doesnt seem like any of the classes changed for these but something must have been over-ridden somewhere. 🤔 

Screenshot 2024-06-10 at 11 57 42 AM
Screenshot 2024-06-10 at 11 57 48 AM

**Comment by colganmeanor** [comment]
Screenshot 2024-06-10 at 12 19 30 PM

I'm not sure if something is wrong with my build, but I dont see the loading spinner shown here when its supposed to, which makes the button height look tiny and then it quickly expands to contain the `Pay` text. 

I tried changing it to display just the loading spinner, and it doesnt seem to be rendering properly - hence the screenshot here.

**Comment by TiagoFuelber** [comment]
> I'm not sure exactly what changed - but something here is affecting the size or styling for some of the text elements on the component.
> 
> It doesnt seem like any of the classes changed for these but something must have been over-ridden somewhere. 🤔
> 
> Screenshot 2024-06-10 at 11 57 42 AM Screenshot 2024-06-10 at 11 57 48 AM

Good catch!
These missing styles were in `bootstrap-utilities` which was only imported in the payment-methods component. Moved it up to `checkout-core` component

**Comment by TiagoFuelber** [comment]
> Screenshot 2024-06-10 at 12 19 30 PM
> 
> I'm not sure if something is wrong with my build, but I dont see the loading spinner shown here when its supposed to, which makes the button height look tiny and then it quickly expands to contain the `Pay` text.
> 
> I tried changing it to display just the loading spinner, and it doesnt seem to be rendering properly - hence the screenshot here.

Good catch as well!

Accidentally replaced the loading spinner for a loading component that doesn't exist 🤦 

Fixed.

**Comment by colganmeanor** [comment]
@TiagoFuelber good fixes on the styling! 

One more thing I noticed - is it possible for the skeleton in the Summary section to account for the natural spacing between the Summary and Payment Methods section? 🤔 

If its too much trouble, I'd say don't even worry about it. But if its an easy adjustment, it would look a little bit nicer. I'll leave it up to you, and approve as is for now. Great work overall!

https://github.com/justifi-tech/web-component-library/assets/87510749/60cdac26-a836-4470-849a-eff1271c0ee8

**Review by colganmeanor — APPROVED** [review]

**Comment by TiagoFuelber** [comment]
> @TiagoFuelber good fixes on the styling!
> 
> One more thing I noticed - is it possible for the skeleton in the Summary section to account for the natural spacing between the Summary and Payment Methods section? 🤔
> 
> If its too much trouble, I'd say don't even worry about it. But if its an easy adjustment, it would look a little bit nicer. I'll leave it up to you, and approve as is for now. Great work overall!
> 
>  Screen.Recording.2024-06-11.at.11.30.12.AM.mov

Nice suggestion!

Fixed 

Jun-11-2024 13-49-42

**Pull request merged**
