### PR TITLE
feat: adds errorEvent to all other components

### PR DESCRIPTION
**Pull request by TiagoFuelber**
This adds an `errorEvent` to the all other components.

Links
-----

#433 

Developer considerations
--------------

- On any task
  - [ ] Previous unit and e2e tests are passing
  - [ ] Perform dev QA
- On new features
  - [ ] Add unit tests
  - [ ] Add documentation

Developer QA steps
--------------------
[ ] - If forced error on any component, the event should be logged in the Storybook actions tab

### CODE REVIEW

**Review by colganmeanor — COMMENTED** [review]
Overall - really great work here! This PR continues to improve our testing, and our error handling logic, and I think we will all feel so much more confident in our code with this coverage! 

I also really like the way you structured and organized the error event details - its a great format, and I think it's one that we can continue to use and grow overtime as we find new ways to use this event to communicate with our users. 

I do have some notes I want to address, in another comment, that I think we should discuss before merging! There are one or two components that I was unable to log the event in the actions panel while I was testing, and there are a few more things I think we should add to this before calling it complete. 

Overall, really great work though. 💪🏻

**Comment by colganmeanor** [comment]
I was doing QA for this task, and going through each component in storybook with this branch to check for the event being logged in the Actions Panel. 

While I was looking around at storybook, I was thinking there are really 3 things that should be in place for each component after this PR is merged: 
1. Event should be logging in the Actions Panel for the component as it is emitted
2. The Event definition should be shown in the Docs / Control Panel for each component that can emit the event (for reference, the way this is done for `payment-form` is perfect IMO)
3. The example code snippet should show how to use this event listener, or we should include an additional snippet that shows event listening. (again, `payment-form`

So, with that in mind - here is my rundown of all the components I could test in this branch, with their status on all 3 of these items: 

`BusinessDetails` 
- Event is shown in Actions panel. ✅
- Event is NOT shown in control panel for story ❌
- Example Updated ❌

`Gross Payment Chart`
- Event is shown in Actions panel. ✅
- Event is NOT shown in control panel for story ❌
- Example Updated ❌

`PaymentDetails`
- Event is NOT shown in Actions panel. ❌
- Event is NOT shown in control panel for story ❌
- Example Updated ❌

`PaymentsList`
- Event is shown in Actions panel. ✅
- Event is NOT shown in control panel for story ❌
- Example Updated ❌

`PayoutDetails`
- Event is shown in Actions panel. ✅
- Event is NOT shown in control panel for story ❌
- Example Updated ❌

`PayoutsList`
- Event is shown in Actions panel. ✅
- Event is NOT shown in control panel for story ❌
- Example Updated ❌

`PaymentForm`
- Event is shown in Actions panel. ❌ (I could not get this one to show! I might need to try again on Monday if you know a best way to force an error)
- Event is shown in control panel for story ✅
- Example Updated ✅

**Comment by TiagoFuelber** [comment]
> I was doing QA for this task, and going through each component in storybook with this branch to check for the event being logged in the Actions Panel.
> 
> While I was looking around at storybook, I was thinking there are really 3 things that should be in place for each component after this PR is merged:
> 
> 1. Event should be logging in the Actions Panel for the component as it is emitted
> 2. The Event definition should be shown in the Docs / Control Panel for each component that can emit the event (for reference, the way this is done for `payment-form` is perfect IMO)
> 3. The example code snippet should show how to use this event listener, or we should include an additional snippet that shows event listening. (again, `payment-form` is a good example of one that has this, while `payments-list` has its own section with a specific code snippet for Event Usage - I think I like this best, personally)
> 
> So, with that in mind - here is my rundown of all the components I could test in this branch, with their status on all 3 of these items:
> 
> `BusinessDetails`
> 
> * Event is shown in Actions panel. ✅
> * Event is NOT shown in control panel for story ❌
> * Example Updated ❌
> 
> `Gross Payment Chart`
> 
> * Event is shown in Actions panel. ✅
> * Event is NOT shown in control panel for story ❌
> * Example Updated ❌
> 
> `PaymentDetails`
> 
> * Event is NOT shown in Actions panel. ❌
> * Event is NOT shown in control panel for story ❌
> * Example Updated ❌
> 
> `PaymentsList`
> 
> * Event is shown in Actions panel. ✅
> * Event is NOT shown in control panel for story ❌
> * Example Updated ❌
> 
> `PayoutDetails`
> 
> * Event is shown in Actions panel. ✅
> * Event is NOT shown in control panel for story ❌
> * Example Updated ❌
> 
> `PayoutsList`
> 
> * Event is shown in Actions panel. ✅
> * Event is NOT shown in control panel for story ❌
> * Example Updated ❌
> 
> `PaymentForm`
> 
> * Event is shown in Actions panel. ❌ (I could not get this one to show! I might need to try again on Monday if you know a best way to force an error)
> * Event is shown in control panel for story ✅
> * Example Updated ✅

@colganmeanor really nice review and suggestions.
This will make our documentations and usage a lot more easy.

I added the `errorEvent` to all docs and examples where it was missing 👍 

Regarding QA of the `payment-form`, the best way I know to test this is the following: 
- Run `payments-js` locally and make the `payment-form` point to this (localhost:3003/v2) on the base-config
- Then in Payments-js, make the tokenize method fail or throw an error. 👍 

Please let me know if this helps

**Comment by colganmeanor** [comment]
> > I was doing QA for this task, and going through each component in storybook with this branch to check for the event being logged in the Actions Panel.
> > While I was looking around at storybook, I was thinking there are really 3 things that should be in place for each component after this PR is merged:
> > 
> > 1. Event should be logging in the Actions Panel for the component as it is emitted
> > 2. The Event definition should be shown in the Docs / Control Panel for each component that can emit the event (for reference, the way this is done for `payment-form` is perfect IMO)
> > 3. The example code snippet should show how to use this event listener, or we should include an additional snippet that shows event listening. (again, `payment-form` is a good example of one that has this, while `payments-list` has its own section with a specific code snippet for Event Usage - I think I like this best, personally)
> > 
> > So, with that in mind - here is my rundown of all the components I could test in this branch, with their status on all 3 of these items:
> > `BusinessDetails`
> > 
> > * Event is shown in Actions panel. ✅
> > * Event is NOT shown in control panel for story ❌
> > * Example Updated ❌
> > 
> > `Gross Payment Chart`
> > 
> > * Event is shown in Actions panel. ✅
> > * Event is NOT shown in control panel for story ❌
> > * Example Updated ❌
> > 
> > `PaymentDetails`
> > 
> > * Event is NOT shown in Actions panel. ❌
> > * Event is NOT shown in control panel for story ❌
> > * Example Updated ❌
> > 
> > `PaymentsList`
> > 
> > * Event is shown in Actions panel. ✅
> > * Event is NOT shown in control panel for story ❌
> > * Example Updated ❌
> > 
> > `PayoutDetails`
> > 
> > * Event is shown in Actions panel. ✅
> > * Event is NOT shown in control panel for story ❌
> > * Example Updated ❌
> > 
> > `PayoutsList`
> > 
> > * Event is shown in Actions panel. ✅
> > * Event is NOT shown in control panel for story ❌
> > * Example Updated ❌
> > 
> > `PaymentForm`
> > 
> > * Event is shown in Actions panel. ❌ (I could not get this one to show! I might need to try again on Monday if you know a best way to force an error)
> > * Event is shown in control panel for story ✅
> > * Example Updated ✅
> 
> @colganmeanor really nice review and suggestions. This will make our documentations and usage a lot more easy.
> 
> I added the `errorEvent` to all docs and examples where it was missing 👍
> 
> Regarding QA of the `payment-form`, the best way I know to test this is the following:
> 
> * Run `payments-js` locally and make the `payment-form` point to this (localhost:3003/v2) on the base-config
> * Then in Payments-js, make the tokenize method fail or throw an error. 👍
> 
> Please let me know if this helps


Great work cleaning up the docs and examples - everything looks much better. I can also confirm that I did successfully get the event logged and appearing in the actions panel for the `payment-form` component. 

Interestingly, when I was testing `payment-form` I received 2 error events in the Actions Panel that were for different things. The first one was expected, it was the error event that was triggered when tokenize failed. 

The second one was related to the submit button somehow. The contained error object had the following info:

```
errorCode: "unknown-error"
message: "this.submitted.emit is not a function"
severity: "error"
```

🤔

**Review by colganmeanor — CHANGES_REQUESTED** [review]
I think that we should change the name of this event from camelCase `errorEvent` to snake-case `error-event` before releasing this PR. 

I don't think there is a standard convention for how javascript events should be named generally, I've seen both conventions before. 

But, since we have already had components documented for a while with events using snake-case (`payment-row-clicked`, `payout-row-clicked`), I feel like we should follow the convention we've already set for ourselves. 

Probably a little annoying to change on all these files, I apologize!

**Review by colganmeanor — APPROVED** [review]

**Comment by colganmeanor** [comment]
Approved! Great work @TiagoFuelber ! 

🦖

**Pull request merged**
