### PR TITLE
Return entire tokenize response from CardForm, BankAccountForm, PaymentForm

### PR DESCRIPTION
**Pull request by jakemer**
Our iframed `payments-js` react app only passes along errors or token to the web components after it gets a response from the `payment_methods` endpoint. It will now return the full response if the web components version is `4.0.0` or greater.

Links
-----

Needs changes in `payments-js`: https://github.com/justifi-tech/payments-js/pull/89

Developer considerations
--------------

- [x] Increment the version number for relevant packages
  - [x] This is a new MAJOR version (incompatible API changes were made)
  - [ ] This is a new MINOR version (functionality was added in a backwards compatible manner)
  - [ ] This is a new PATCH version (backwards compatible bug fixes)
- [x] Update the CHANGELOG.md with a summary of the changes
  - If this is a MAJOR version, what are the breaking API changes? Was anything added to the API?
  - If this is a MINOR version, what feature was added? Why would consumers want this new version?
  - If this is a PATCH version, what was fixed?
- [x] Update the appropriate documentation. Keep in mind that this mono repository has README files at the repository, project, and component levels. We want developers to be able to find what they need from the main README, so make sure to add links to component documentation if adding something new.

Steps for Testing/QA
--------------------
### Components before `4.0.0`
- Pull main
- See that the version in `stencil-library/package.json` is less than `4.0.0`
- Run `yarn && yarn build && yarn start` from the `stencil-library` directory
- Storybook should open at `localhost:6006`
- Navigate to `PaymentForm`
- Set the iframe-url to `https://js.justifi-staging.com/v2`
- Set the `client-id` to a valid client id for a staging
- Enter an email for the `email` field
- Fill out the payment form and click "Submit"
- [x] In the browser developer console, the response should have been logged and should be in the format of`{ token: <the-token> }`
- [x] Repeat but with an invalid client id. The response should have been logged in the format of `{ errors: ['some-error'] }`

### Components at or above version `4.0.0`
- Pull this branch
- See that the version in `stencil-library/package.json` is `4.0.0`
- Repeat the rest of the steps from  the "Components before `4.0.0`" scenario
- [x] In the browser developer console, the response should have been logged and should be in the format outlined by our API docs [here](https://developer.justifi.ai/tag/Payment-Methods#operation/CreatePaymentMethod)
- [x] Repeat but with an invalid client id. The error response should be the same as you would get by running the `curl` command (with same arguments) found in our docs:
```
curl -i -X POST \
  https://api.justifi.ai/v1/payment_methods \
  -H 'Authorization: string' \
  -H 'Content-Type: application/json' \
  -H 'Idempotency-Key: 497f6eca-6276-4993-bfeb-53cbbbba6f08' \
  -H 'Seller-Account: string' \
  -H 'Sub-Account: string' \
  -d '{
    "payment_method": {
      "card": {
        "name": "Lindsay Whalen",
        "number": 4242424242421111,
        "verification": 123,
        "month": 5,
        "year": 2042,
        "address_postal_code": 55555,
        "metadata": {
          "new": "info"
        }
      }
    }
  }'
```
- [x] Sign off on the corresponding payments-js PR: https://github.com/justifi-tech/payments-js/pull/89

### CODE REVIEW

**Review by colganmeanor — APPROVED** [review]

**Comment by krististepanek** [comment]
Not sure if this is right - when running the components locally on main at version 3.0.4, I got this logged in the console - it looks like the entire payment_method response.  The errors one looks okay though.
Screen Shot 2023-05-10 at 1 29 31 PM

**Review by Cherna — APPROVED** [review]
Not sure this is a major version, since it adds.

**Comment by jakemer** [comment]
@Cherna The reason it's a major version is because it's a breaking change. The implementer will need to change how they handle the data returned to them via submit or tokenize

**Comment by jakemer** [comment]
@krististepanek Yeah, that does not look correct at all. I will take a look tomorrow

**Comment by jakemer** [comment]
@krististepanek I need to re-stage my payments-js branch

**Review by krististepanek — APPROVED** [review]
🐝

**Review by colganmeanor — APPROVED** [review]

**Review by Cherna — APPROVED** [review]

**Review by TiagoFuelber — APPROVED** [review]
LGTM

**Review by krististepanek — APPROVED** [review]
🪲

**Pull request merged**
